### ISSUE TITLE
在 crosswalk 下无法定位

### ISSUE THREAD

**Issue by Hanruis** [darkgeek/Phonegap-BaiduGeolocation-Plugin#3]
抱歉，因为不懂java，又来打扰你了。

在 cordova 项目中，替换掉原生的 webview ，使用 crosswalk，这个插件无法定位。( ps：现在 crodova 支持通过插件来替换原生的 webview  )

具体的 log 如下：

```
com.carisok.expert D/BaiduGeolocation﹕ Start Geolocation service.
com.carisok.expert:remote D/baidu_location_service﹕ baidu location service start1 ...11975
com.carisok.expert D/baidu_location_client﹕ baidu location connected ...
com.carisok.expert:remote W/System.err﹕ java.lang.UnsatisfiedLinkError: Couldn't load locSDK4d from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.carisok.expert-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.carisok.expert-1, /vendor/lib, /system/lib]]]: findLibrary returned null
com.carisok.expert:remote W/System.err﹕ at java.lang.Runtime.loadLibrary(Runtime.java:358)
com.carisok.expert:remote W/System.err﹕ at java.lang.System.loadLibrary(System.java:526)
com.carisok.expert:remote W/System.err﹕ at com.baidu.location.Jni.<clinit>(Unknown Source)
com.carisok.expert:remote W/System.err﹕ at com.baidu.location.ai$a.T(Unknown Source)
com.carisok.expert:remote W/System.err﹕ at com.baidu.location.aa.run(Unknown Source)
com.carisok.expert:remote W/dalvikvm﹕ Exception Ljava/lang/IllegalStateException; thrown while initializing Lcom/baidu/location/Jni;
com.carisok.expert:remote W/dalvikvm﹕ threadid=13: thread exiting with uncaught exception (group=0x416cdd58)
com.carisok.expert:remote I/dalvikvm﹕ Rejecting re-init on previously-failed class Lcom/baidu/location/Jni; v=0x0
com.carisok.expert:remote I/dalvikvm﹕ Rejecting re-init on previously-failed class Lcom/baidu/location/Jni; v=0x0
com.carisok.expert:remote W/dalvikvm﹕ threadid=13: thread exiting with uncaught exception (group=0x416cdd58)
com.carisok.expert:remote I/dalvikvm﹕ Rejecting re-init on previously-failed class Lcom/baidu/location/Jni; v=0x0
com.carisok.expert:remote I/dalvikvm﹕ Rejecting re-init on previously-failed class Lcom/baidu/location/Jni; v=0x0
com.carisok.expert:remote W/dalvikvm﹕ threadid=13: thread exiting with uncaught exception (group=0x416cdd58)
com.carisok.expert:remote I/dalvikvm﹕ Rejecting re-init on previously-failed class Lcom/baidu/location/Jni; v=0x0
```

**Comment by darkgeek** [comment]
你好，看到它抛出的异常“`Couldn't load locSDK4d`”，请先检查插件的`/src/android`目录下是否有`liblocSDK4d.so`这个文件。

**Comment by Hanruis** [comment]
在插件的目录下没有，在 android 项目里面也没有。

我刚切换回来原生的 webview ，能够正常定位，同样是没有 liblocSDK4d.so 文件。

**Comment by darkgeek** [comment]
你可以试着把 [liblocSDK4d.so](https://github.com/darkgeek/Phonegap-BaiduGeolocation-Plugin/blob/master/src/android/liblocSDK4d.so?raw=true) 放到插件的/src/android目录下，再试一下。

**Comment by Hanruis** [comment]
抱歉，发现是有这个插件的。（ 上面说没有，是因为 sublime text 不识别还是什么的，在文件目录里面找不到。 ）

现在的情况是：
src/android/ -- 有
platforms\android\libs\armeabi -- 有。

**Comment by darkgeek** [comment]
不好意思，现在手边只有一台2.3的机子（crosswalk需要4.0以上），所以暂时不大好测试和修复。容我再想想办法。

**Comment by Hanruis** [comment]
嗯嗯，不急不急，就是发现这个问题，和你说一下哈 : )  

希望这个插件能够越来越好哈~

**Comment by jaken-deng** [comment]
路过，表示遇到同样的问题，求解

**Comment by Hanruis** [comment]
弱弱的过来问下，bug 是否有相应的进展了。

**Comment by darkgeek** [comment]
@Hanruis 不好意思，最近在忙着看书找工作，还要准备毕业论文，一时半会抽不出时间。等忙完这阵子，我一定好好解决这个问题。

**Comment by Hanruis** [comment]
@darkgeek thanks，哈哈，原来你还没有毕业。真心给力哈~~
